name: aft_firebase_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # Runtime packages
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
