name: aft_firebase_app
description: "Most up-to-date AFT calculator"
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ^3.5.3
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # Runtime packages
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  app_links: ^7.0.0
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.3
  google_sign_in: ^6.2.1
  flutter_riverpod: ^3.1.0
  path_provider: ^2.1.3
  state_notifier: ^1.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdf: ^32.1.21
  syncfusion_flutter_pdfviewer: ^32.1.21
  package_info_plus: ^9.0.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  pdf: ^3.11.0
  printing: ^5.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
  fake_cloud_firestore: ^4.0.1
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/ranks/
    - assets/forms/
    - assets/forms/
    - assets/onboarding/
